RSRP_GOOD_THRESH = -80 # A good RSRP is > RSRP_GOOD_THRESH
RSRP_ACCEPTABLE_THRESH = -100 # An acceptable RSRP is > RSRP_ACCEPTABLE_THRESH
RSRQ_GOOD_THRESH = -10 # A good RSRQ is > RSRQ_GOOD_THRESH
RSRQ_ACCEPTABLE_THRESH = -15 # An acceptable RSRQ is > RSRQ_ACCEPTABLE_THRESH

