RSRP_GOOD_THRESH = -80 # A good RSRP is > RSRP_GOOD_THRESH
RSRP_ACCEPTABLE_THRESH = -100 # An acceptable RSRP is > RSRP_ACCEPTABLE_THRESH
RSRQ_GOOD_THRESH = -10 # A good RSRQ is > RSRQ_GOOD_THRESH
RSRQ_ACCEPTABLE_THRESH = -15 # An acceptable RSRQ is > RSRQ_ACCEPTABLE_THRESH\
RSRQ_UNUSABLE_THRESH = -20 # An unusable RSRQ is < RSRQ_UNUSABLE_THRESH
RSRP_UNUSABLE_THRESH = -120 # An unusable RSRP is < RSRP_UNUSABLE_THRESH
DISCRETE_COLOR_MAP = {1: {"r": 1.0, "g": 0.2, "b": 0.2}, 2: {"r": 1.0, "g": 1.0, "b": 1.0}} # Maps kpi values to colors
