#!/usr/bin/env python3
import socket
import os
import argparse

HOST = "0.0.0.0"  # The server's hostname or IP address
COMMAND_PORT_ANDROID = 12345  # The port at the which the Android App listens for commands
DATA_PORT = 12348 # The port on this compute node, to which the Android App sends measurements

PORT_FORWARD_COMMAND = "adb forward tcp:" + str(COMMAND_PORT_ANDROID) + " tcp:" + str(COMMAND_PORT_ANDROID)
PORT_REVERSE_COMMAND = "adb reverse tcp:" + str(DATA_PORT) + " tcp:" + str(DATA_PORT)


def sendToPhone(command):
    os.system(PORT_FORWARD_COMMAND)
        
    if "start" in command:
        os.system(PORT_REVERSE_COMMAND)
        
    command = command + "\n"

    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(5)
            s.connect((HOST, COMMAND_PORT_ANDROID))
            print("Connected to Android. Sending command: " + str(command))
            s.send(bytes(command, "utf-8"))
            data = s.recv(1024)
            print("Response from android: " + data.decode())
            
    except socket.timeout as e:
        print("Timeout waiting for a response from PawPrints.")

    except ConnectionRefusedError:
        print("Connection refused by PawPrints. Check if the phone is connected and adb is configured properly.")



parser = argparse.ArgumentParser()
parser.add_argument('command', type=str, help='command to be sent to PawPrints phone app')
args = parser.parse_args()

if args.command is not None:
    sendToPhone(args.command)

